// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kvtxiabpwkjbxicjygqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt2dHhpYWJwd2tqYnhpY2p5Z3F3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwNjA3OTIsImV4cCI6MjA3MTYzNjc5Mn0.JqQ7_xLLb6wEdlIC4i63Cd9PByW8rFnQbUwHIyWMwIQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});